version: '3'
services:
  monolithic:
    build:  .
    entrypoint: []
    ports:
      - "8090:8000"
    environment:
      - SHOP_MONOLITHIC_BIND_ADDR=:8000
    volumes:
      - ./cmd/:$GO_PROJECT_DIR/cmd/
      - ./pkg/:$GO_PROJECT_DIR/pkg/
      
  orders:
    build: .
    entrypoint: []
    ports:
      - "8070:8000"
    environment:
      - SHOP_ORDER_SERVICE_BIND_ADDR=:8000
      - SHOP_RABBITMQ_ADDR = rabbitmq:5672
      - SHOP_RABBITMQ_ORDERS_TO_PAY_QUEUE = orders-to-payments
      - SHOP_SHOP_SERVICE_ADDR=http://shop:8080
    volumes:
    depends_on:
      - rabbitmq
    
  payments:
    build: .
    entrypoint: []
    volumes:
      -
    environment:
      - SHOP_RABBITMQ_ADDR=rabbitmq:5672
      - SHOP_RABBITMQ_ORDERS_TO_PAY_QUEUE=orders-to-pay 
      - SHOP_ORDERS_SERVICE_ADD=http://orders:8000
    depends_on:
      - rabbitmq
  shop:
    build: .
    entrypoint: []
    volumes:
    environment:
      - SHOP_SHOP_SERVICE_BIND_ADDR=:8000
    ports:
      - "8071:8000"
    depends_on:
      -  rabbitmq
